FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    libonig-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    curl \
    libssl-dev \
    && docker-php-ext-install pdo_mysql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY ./microservice /var/www/html

RUN apt -y install zsh

RUN composer install --no-interaction --prefer-dist --optimize-autoloader

RUN composer require illuminate/database
RUN composer require firebase/php-jwt

EXPOSE 9000
CMD ["php-fpm"]
