version: '3.8'

services:
    php:
        build:
            context: ./backend_php_message
            dockerfile: docker/php/dockerfile
        container_name: my_microservice_php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        environment:
            - APP_ENV=local
            - DB_HOST=db
            - DB_DATABASE=mydb
            - DB_USER=root
            - DB_PASS=password
            - JWT_SECRET=secret_key_jwt
        depends_on:
            - db

    nginx:
        build:
            context: ./backend_php_message/docker/nginx
            dockerfile: dockerfile
        container_name: my_microservice_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - php

    react:
        build:
            context: ./frontend_react
            dockerfile: Dockerfile
        container_name: my_microservice_react
        ports:
            - "4200:4200"
        environment:
            - PORT=4200
        volumes:
            - ./frontend_react:/app
            - /app/node_modules

    db:
        image: mysql:8.0
        container_name: my_microservice_db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mydb
        ports:
            - "3305:3305"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db_data:/var/lib/mysql

    mongo_discussion:
        image: mongo:6.0
        container_name: my_microservice_mongo_discussion
        restart: always
        environment:
            MONGO_INITDB_DATABASE: discussion_db
        ports:
            - "27017:27017"
        volumes:
            - mongo_discussion_data:/data/db


    node_discussion:
        build: ./backend_node_discussion
        container_name: my_microservice_node_discussion
        ports:
            - "5555:5555"
        environment:
            - PORT=5555
            - MONGO_URI=mongodb://mongo_discussion:27017/discussion_db
            - JWT_SECRET=your_jwt_secret_key
        volumes:
            - ./backend_node_discussion:/usr/src/app
            - /usr/src/app/node_modules
        command: [ "npm", "run", "dev" ]
        depends_on:
            - mongo_discussion

    backend_node_connector:
        build: ./backend_node_connector
        container_name: my_microservice_connector
        ports:
            - "3000:3000"
        volumes:
            - ./backend_node_connector:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - PORT=3000
            - JWT_SECRET=your_jwt_secret_key
            - PHP_BACKEND_URL=http://nginx:80
            - DISCUSSION_BACKEND_URL=http://node_discussion:5555/api/discussions
        command: [ "npm", "run", "dev" ]
        depends_on:
            - php
            - node_discussion

volumes:
    db_data:
    mongo_discussion_data:
