version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/dockerfile
        container_name: my_microservice_php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        environment:
            - APP_ENV=local
            - DB_HOST=db
            - DB_DATABASE=mydb
            - DB_USER=root
            - DB_PASS=password
            - JWT_SECRET=secret_key_jwt
        depends_on:
            - db

    nginx:
        build: docker/nginx
        container_name: my_microservice_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - php

    db:
        image: mysql:8.0
        container_name: my_microservice_db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mydb
        ports:
            - "3305:3305"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
